services:
  app:
    build:
      context: ./portal-web
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes: 
      - ./portal-web/app/:/app/app
      - ./portal-web/data/:/app/data