site_name: Portal A+zonia
repo_url: https://github.com/unb-mds/2024-2-Squad10

nav:
  - Home: index.md
  - Sprints:
    - Sprint 0: sprints/sprint0.md
    - Sprint 1: sprints/sprint1.md
theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "indigo"
  font:
    text: "Roboto"
    code: "Roboto Mono"